from resources.BaseResource import BaseResource

#INSIDE THE DIR OF THE USER (COMPANY)
#WHEN HE STARTS A VISIT AND CREATES A CLIENT 
#--> CREATE A DIR OF THE CLIENT
    #-> CREATE A DIR OF THE VISIT
#WHEN USER CREATES AN ADDRESS
        #-> CREATE A DIR OF THE ADDRESS
#WHEN USER CREATES A ROOM
            #-> CREATE A DIR OF THE ROOM
#WHEN USER ADDS A FURNITURE WITH IMAGE
#ADD FURNITURE TO INVENTORY
                #NAME THE IMAGE : IdFurniture_CatalogueName_ImageNumber
#ADD THIS PATH TO DATABSE IMAGE RESOURCE

#class ImageResource(BaseResource):

